In [2]:
import allensdk.brain_observatory.behavior.behavior_project_cache as bpc
import pandas as pd

my_cache_dir = '/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/allensdk_visualbehavior_cache'

bc = bpc.VisualBehaviorOphysProjectCache.from_s3_cache(cache_dir=my_cache_dir)

bs1 = bc.get_behavior_session(870987812)
          
behavior_session_table = bc.get_behavior_session_table()  

mouse_id = 445002

this_mouse_table = behavior_session_table.query('mouse_id == @mouse_id').sort_values(by = 'date_of_acquisition')

cols_to_show = [
    'mouse_id',
    'date_of_acquisition',
    'session_type',
    'prior_exposures_to_session_type', 
    'prior_exposures_to_image_set'
]
this_mouse_table[cols_to_show]

,mouse_id,date_of_acquisition,session_type,prior_exposures_to_session_type,prior_exposures_to_image_set
behavior_session_id,,,,,
837658854,445002,2019-03-15 14:49:24.015,TRAINING_0_gratings_autorewards_15min,0,NaN
838515247,445002,2019-03-18 13:44:01.474,TRAINING_1_gratings,0,NaN
839219841,445002,2019-03-19 12:50:12.068,TRAINING_1_gratings,1,NaN
839565422,445002,2019-03-20 13:16:44.461,TRAINING_1_gratings,2,NaN
839912316,445002,2019-03-21 12:54:25.388,TRAINING_2_gratings_flashed,0,NaN
840581827,445002,2019-03-22 12:56:37.162,TRAINING_2_gratings_flashed,1,NaN
841426832,445002,2019-03-25 13:33:53.275,TRAINING_3_images_A_10uL_reward,0,NaN
841827774,445002,2019-03-26 12:43:01.470,TRAINING_3_images_A_10uL_reward,1,NaN
842385277,445002,2019-03-27 12:13:04.923,TRAINING_3_images_A_10uL_reward,2,NaN
842819933,445002,2019-03-28 12:11:36.413,TRAINING_4_images_A_training,0,NaN
843400453,445002,2019-03-29 13:03:16.029,TRAINING_5_images_A_epilogue,0,NaN
844199758,445002,2019-04-01 11:59:06.026,TRAINING_5_images_A_handoff_ready,0,NaN
844908261,445002,2019-04-02 12:34:16.170,TRAINING_5_images_A_handoff_ready,1,NaN
845572044,445002,2019-04-03 12:16:13.522,TRAINING_5_images_A_handoff_ready,2,NaN
846331423,445002,2019-04-04 13:13:13.399,OPHYS_0_images_A_habituation,0,0.0
847036328,445002,2019-04-05 12:47:32.422,OPHYS_0_images_A_habituation,1,1.0
847874940,445002,2019-04-08 13:27:21.095,OPHYS_0_images_A_habituation,2,2.0
848613406,445002,2019-04-09 13:26:26.372,OPHYS_1_images_A,0,3.0
849147676,445002,2019-04-10 13:34:39.264,OPHYS_2_images_A_passive,0,4.0
849651275,445002,2019-04-11 12:31:50.074,OPHYS_3_images_A,0,5.0
850989832,445002,2019-04-12 13:30:27.946,OPHYS_4_images_B,0,0.0
851773928,445002,2019-04-15 12:20:00.123,OPHYS_5_images_B_passive,0,1.0
852451567,445002,2019-04-16 12:24:46.804,OPHYS_6_images_B,0,2.0
855200229,445002,2019-04-22 09:01:33.022,OPHYS_5_images_B_passive,1,3.0

In [11]:
ophys_session_table = bc.get_ophys_session_table()    
this_mouse_ophys_table = ophys_session_table.query('mouse_id == @mouse_id').sort_values(by = 'date_of_acquisition')

this_mouse_ophys_table[cols_to_show]

,mouse_id,date_of_acquisition,session_type,prior_exposures_to_session_type,prior_exposures_to_image_set
ophys_session_id,,,,,
848264483,445002,2019-04-09 17:15:25.000000,OPHYS_1_images_A,0,3.0
848894137,445002,2019-04-10 16:46:31.000000,OPHYS_2_images_A_passive,0,4.0
849597937,445002,2019-04-11 18:56:20.000000,OPHYS_3_images_A,0,5.0
850959102,445002,2019-04-12 19:52:29.000000,OPHYS_4_images_B,0,0.0
852326785,445002,2019-04-16 18:52:04.000000,OPHYS_6_images_B,0,2.0
855083235,445002,2019-04-22 14:29:07.000000,OPHYS_5_images_B_passive,1,3.0

In [6]:
dir(bc)

['BEHAVIOR_SESSIONS_KEY',
 'MANIFEST_CONFIG',
 'MANIFEST_VERSION',
 'OPHYS_EXPERIMENTS_KEY',
 'OPHYS_SESSIONS_KEY',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_log',
 'add_manifest_paths',
 'build_manifest',
 'cache',
 'cache_csv',
 'cache_csv_dataframe',
 'cache_csv_json',
 'cache_json',
 'cache_json_dataframe',
 'cacher',
 'csv_writer',
 'fetch_api',
 'fetch_tries',
 'from_lims',
 'from_local_cache',
 'from_s3_cache',
 'get_behavior_ophys_experiment',
 'get_behavior_session',
 'get_behavior_session_table',
 'get_cache_path',
 'get_ophys_experiment_table',
 'get_ophys_session_table',
 'json_remove_keys',
 'json_rename_columns',
 'load_csv',
 'load_json',
 'load_manifest',
 'logger',
 'manifest',
 'manifest_dataframe',
 'manifest_path',
 'nocache_dataframe',
 'nocache_json',
 'pathfinder',
 'remove_keys',
 'rename_columns',
 'wrap']

In [13]:
bs1 = bc.get_behavior_session(870987812)

behavior_session_870987812.nwb: 100%|██████████| 51.7M/51.7M [00:04<00:00, 12.4MMB/s]